#!/bin/bash

# Environment Control
alias venv='python3 -m venv .env'
alias src='. .env/bin/activate'
alias deac='deactivate'
alias pipup='pip install --upgrade pip'

# Git aliases
alias gadd='git add'
alias gcom='git commit'
alias gcam='git commit -am'
alias gcek='git checkout'
alias gsta='git status'
alias gdif='git diff'
alias gbra='git branch'
alias gpush='git push'
alias gpus=gpush
alias gpull='git pull'
alias gpul=gpull
alias gclone='git clone'
alias gclo=gclone
alias gfetch='git fetch'
alias gfet=gfetch

# screen control
alias scr='screen'
alias scrs='screen -S'
alias scrr='screen -r'
alias scrls='screen -ls'
alias scrl=scrls
killscr () {
  screen -X -S $1 quit
}

# tmux control
alias tn='tmux new -t'
alias ta='tmux a -t'
alias tls='tmux ls'

# Folder Navigation;
alias cd..='cd ..'
alias ..=cd..
alias cddot='cd $HOME/.dotfiles'
alias cdwork='cd $HOME/Workspaces/'
alias cdwur='cd $HOME/Workspaces/WUR/'

# Latex
alias overpull='xclip -sel c < $HOME/.overleaf.au | gpull'

# Extras
alias please='sudo'
alias hist='history | grep'

# Django
alias pmr='python manage.py runserver'

# Jupyter
alias jnote='jupyter notebook --no-browser'
alias jnotescr='screen -S jnote bash -c "source .env/bin/activate; jupyter notebook --no-browser"'
alias jlab='jupyter lab'
alias jlabscr='screen -S jlab bash -c "source .env/bin/activate; jupyter lab"'

# ls and ls color
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lah'
if [ -x /usr/bin/dircolors ]; then
    test -r $HOME/.dircolors && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands. Use like so: sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
